### ISSUE TITLE
Computing speed percentile from daily increment histograms

### ISSUE THREAD

**Issue by lily-chai** [mapbox/speed-percentile#1]
## Goal

On a given day, for each edge, compute the *p*-th percentile speed for this edge from past *N* days' worth of daily speed histogram.

This script is the daily aggregates script for [nextgen speedracer](https://github.com/mapbox/speedracer/issues/74) (scroll down to **Fixes?** -> **Daily aggregates**).

## Input Data

Increment JSON files outputted by speedracer.<br>
Example:
```
{"a":65285808,"b":1260360887,"increments":{"27":1,"28":1,"29":1,"30":1,"34":1,"35":1,"36":1,"37":4,"38":2,"40":1,"42":1,"47":1,"51":1,"56":1,"58":1,"59":2,"60":1}}
{"a":1260360887,"b":1260360824,"increments":{"26":1,"28":1,"29":1,"30":1,"34":2,"35":1,"37":1,"38":2,"39":2,"40":1,"41":1,"50":1,"51":1,"59":2,"60":1,"63":1}}
{"a":1260360824,"b":1260360924,"increments":{"14":1,"21":1,"26":1,"29":1,"34":1,"35":1,"37":2,"38":2,"39":2,"40":1,"41":2,"43":1,"44":1,"45":1,"46":1,"50":1,"52":1,"59":1,"60":1,"63":1,"69":1}}
{"a":1260360924,"b":1260360819,"increments":{"10":1,"14":1,"21":1,"26":1,"34":1,"35":1,"37":2,"38":2,"39":2,"40":1,"41":3,"42":1,"43":2,"44":1,"46":1,"50":1,"52":1,"60":1,"63":1,"69":2,"138":1}}
```
`increments` = histogram of speeds observed on that one day.

## Output

CSV files of the *p*-th percentile speed for each edge.<br>
Schema:

| column | description |
|:--:|:--:|
| nodeA | starting node ID |
| nodeB | ending node ID |
| speed | *p*-th percentile speed [kph] |

## To-Do

* [x] ~~aggregate increment histograms from the past *N* days~~
    * [x] ~~for a single JSON file: parse histogram~~
        * [x] confirm with @morganherlocker: histograms from speedracer are in buckets of 1 kph
    * [x] ~~wrap in a loop that enumerates through *N* days of increment data~~

* [x] compute percentiles
    * [x] for a single edge: compute the *p*-th percentile
    * [x] ~~wrap in a loop that enumerates through all edges~~

* [x] ~~write out profile CSV~~

<br>
/cc: @morganherlocker

**Comment by morganherlocker** [comment]
👍 Looking fantastic.

> confirm with @morganherlocker: histograms from speedracer are in buckets of 1 kph

This is correct, although we may want to allow for other units as well (mph, m/s, etc). Regardless of unit used, they will always be rounded integers.

> Increment JSON files outputted by speedracer.

Per voice, we can make this implementation a bit more generic by accepting only the speed histogram as a parameter to the library's function. The details of which nodes are being looked at can be ignored, since they are not relevant to the percentile calculation. This should let us use this library for other types of statistics like "What is the 80th percentile speed for all freeways in California?" or "What is the 70th percentile speed for way number 12345?"

Proposed interface example:

```js
var speedPercentile = require('speed-percentile');

var speeds = {"27":1,"28":1,"29":1,"30":1,"34":1,"35":1,"36":1,"37":4,"38":2,"40":1,"42":1,"47":1,"51":1,"56":1,"58":1,"59":2,"60":1};
var p = 0.9;

console.log(speedPercentile(speeds, 0.9)) // 42
```

**Comment by lily-chai** [comment]
Crossed out tasks in the original issue that do not apply to the proposed interface.
